### ISSUE TITLE
Feature Request to add Gong H-Alpha Data

### ISSUE THREAD

**Issue by AlisonJarvis** [jmbhughes/solarannotator#3]

**Comment by jmbhughes** [comment]
Thanks. I'll look into this as we discussed.

**Comment by jmbhughes** [comment]
@AlisonJarvis, it seems like this may be a bit more complicated as there's no map source for GONG h-alpha in SunPy right now (https://github.com/sunpy/sunpy/issues/6656). I did hack something together and could add that. 

<img width="690" alt="Screen Shot 2023-01-21 at 3 57 44 PM" src="https://user-images.githubusercontent.com/13068381/213890337-6ac8b01e-bb45-486d-969b-c2381b255897.png">

I will see if we can get the

**Comment by AlisonJarvis** [comment]
@jmbhughes That looks great! Does there being no map source for GONG H-Alpha mean that it would not be not co-aligned with the SUVI data? Or did your hacked solution resolve that somehow?

**Comment by jmbhughes** [comment]
@AlisonJarvis I think it works to co-align, but I'm not 100% certain it's correct.
